/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dgcCrowndsaleSol from "./DGCCrowndsale.sol";
export type { dgcCrowndsaleSol };
import type * as heroSol from "./Hero.sol";
export type { heroSol };
export type { Auction } from "./Auction";
export type { DauGia } from "./DauGia";
export type { HeroMarketplace } from "./HeroMarketplace";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
