/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dgcCrowndsaleSol from "./DGCCrowndsale.sol";
export * as heroSol from "./Hero.sol";
export { Auction__factory } from "./Auction__factory";
export { DauGia__factory } from "./DauGia__factory";
export { HeroMarketplace__factory } from "./HeroMarketplace__factory";
export { USDT__factory } from "./USDT__factory";
export { Vault__factory } from "./Vault__factory";
